### ISSUE TITLE
docker-compose:pihole-traefik

### ISSUE THREAD

**Issue by Wonderbox2000** [Mettmett/docker-compose#12]
Bonjour Mettmett,

merci pour vos nombreux modèles de configurations. Je m'interresse de près à celui permettant à traefik de router le traffic dns et page admin de pihole.

Sur mon navigateur quand je vais sur http://home:8080 - j'ai le dashboard de Traefik.
Neanmoins, quand je vais sur http://home/pihole ou http://home/traefik > rien ! 
                  
**Voici mon docker-compose.yml pour Traefik:**

```
version: '3'
services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 1194:1194/udp
      - 1195:1195
      - 53:53/udp
      - 53:53
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/dynamic:/etc/traefik/dynamic:ro
      - /var/log:/var/log
    environment:
      - "TZ=Europe/Paris" #ajout d'une variable de TimeZone

networks:
  proxy:
    external: true
```

**traefik.yml**:
```
api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  openvpn:
    address: ":1194/udp"
  metrics:
    address: ":1195"
  udpdns:
    address: ":53/udp"
 
#grafana
metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
#grafana
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true

certificatesResolvers:
  http:
    acme:
      email: xxx@xxx.fr
      storage: acme.json
      httpChallenge:
        entryPoint: http


accessLog:
  filePath: "/var/log/traefik/access.log"
  fields:
    defaultMode: keep
    names:
      StartUTC: drop
    headers:
      defaultMode: keep
```

**mon services.yml** :
```
http:
    services:
        sc-pihole:
           loadBalancer:
               servers:
                   - url: "http://192.168.1.253:80"

udp:
  services:
    sc-pihole-udp:
      loadBalancer:
        servers:
          - address: "udp://192.168.1.253:53"`
```
**routers.yml**:
```
http:
  `routers:
    rt-traefik:
      entryPoints:
        - http
      service: dashboard@internal
      rule: PathPrefix(`/traefik`)

    rt-pihole:
      entryPoints:
        - http
      service: sc-pihole
      rule: PathPrefix(`/pihole`)
udp:
  routers:
    udp-pihole:
      entryPoints:
        - udpdns
      service: sc-pihole-udp
```

Est ce que vous pourriez m'aider s'il vous plait ?
